# Generated by Django 3.2.16 on 2024-01-08 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fragnances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragnancecomment',
            options={'verbose_name': 'Отзывы про духи', 'verbose_name_plural': 'Отзывы про духи'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping_list', 'verbose_name': 'Список для покупок', 'verbose_name_plural': 'Списки для покупок'},
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='fragnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='fragnances.fragnance', verbose_name='Духи'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together=set(),
        ),
    ]
