# Generated by Django 3.2.16 on 2024-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragnances', '0002_auto_20240108_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragnance',
            name='description',
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
