# Generated by Django 3.2.16 on 2024-01-08 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragnances', '0003_fragnance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragnance',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
