# Generated by Django 3.2.16 on 2024-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragnances', '0005_alter_favourite_fragnance_alter_favourite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragnance',
            name='sex',
            field=models.CharField(default='Унисекс', max_length=8),
        ),
        migrations.AddField(
            model_name='fragnance',
            name='type',
            field=models.CharField(default='Товар', max_length=20),
        ),
    ]
